---
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U flake8
  - pip install -U mock
  - pip install codecov
install:
  - pip install ".[test]" .  # install package + test dependencies
before_script:
  # 127 are the length of a line in the github-editor
  - flake8 --count --exclude ./tests,./doc --max-complexity 20 --max-line-length 127 --statistics
script: pytest  # run tests
after_success:
  - codecov  # submit coverage
